### ISSUE TITLE
Add Makefile target for resetting run results

### ISSUE THREAD

**Issue by LazaroHurtado** [gkamradt/LLMTest_NeedleInAHaystack#23]
We provide devs with a make command for cleaning pycache and destroying their venv. I think it would be nice to include a command for deleting `results/` and `contexts/` since I myself found it useful. This command would not be a prereq to destory and will stand by itself so devs dont accidentally lose their analysis

**Comment by kedarchandrayan** [comment]
Fixed by #24.
