### ISSUE TITLE
Azure OpenAI key

### ISSUE THREAD

**Issue by cobraheleah** [gkamradt/LLMTest_NeedleInAHaystack#3]
Does it support Azure OpenAI key? if support ,how to set it?
 thank you very much

**Comment by gkamradt** [comment]
Not yet, right now it is just Anthropic and OpenAI

I would have normally just implemented this with LangChain directly so you could swap whatever models you wanted for testing and eval but the Anthropic crew wanted me to avoid LangChain for their test and call their api directly.

I'm open to have someone help with a PR to change this but it hasn't made it to my top priority yet.

**Comment by cobraheleah** [comment]
ok，i get it，thank you very much
