### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by haesleinhuepf** [gkamradt/LLMTest_NeedleInAHaystack#4]
Hi @gkamradt ,

that's a fantastic repository! I was just wondering under which conditions one could reuse the code ansd materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by gkamradt** [comment]
Nice! thank you for the comment Robert! I'm going to add one now. I'm not too familiar with all the types but it'll be the one that says "use this however you want (commercial/projects), please give attribution"

**Comment by haesleinhuepf** [comment]
That sounds like BSD:
https://opensource.org/license/bsd-3-clause/

Thanks!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Awesome, thanks! It's not obvious which line is modified. But anyway, now I can legally reuse your code and show the great figures in my teaching materials, of course mentioning you and the source. Big thanks for the quick response!
